### ISSUE TITLE
Can't Avoid Swift Convert

### ISSUE THREAD

**Issue by arapocket** [devin-la/ionic-video-chat-support#92]
Trying to build the app using in the CLI fails. When I open up the project in Xcode I get a message saying the project is using outdated SWIFT code. 

Not converting it results in a failed build, converting it results in a failed build.

**Comment by arapocket** [comment]
I followed the instructions at https://github.com/devin-la/ionic-video-chat-v2-issues/wiki/Building#ios and the link in that page to no avail.

**Comment by pkitatta** [comment]
I wanted to purchase this for my project but holding back because am weary of the creator's response if something is not working. I will simply watch the repo for activity from Davin before I purchase.

**Comment by raviada** [comment]
This seems like waste of time.. I spent almost 4hrs trying to fix it, the only option left to try is to downgrade xcode to 8.2, but I am afraid it breaks any other projects...
If the author upgrades Swift to 3.0 then it may worth spending money.. I already spent my $25, may be down the drain...

**Comment by casper123** [comment]
Any updates on this?

**Comment by arapocket** [comment]
Nope. He told me he would fix it. Then eventually disappeared into the bushes.

**Comment by casper123** [comment]
Lol looks like we're have to find other way around

**Comment by arzynik** [comment]
upgraded to ionic 3 and swift 3.

a new version is available on the ionic marketplace
