### ISSUE TITLE
TypeError: AppScripts.serve is not a function

### ISSUE THREAD

**Issue by ghost** [devin-la/ionic-video-chat-support#94]
λ ionic serve

? Detected PROXY in environment, but to proxy CLI requests, you'll need @ionic/cli-plugin-proxy installed. Install now?  No
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 - Ctrl+C to cancel
TypeError: AppScripts.serve is not a function

**Comment by arzynik** [comment]
this was an issue with old cli scripts. download the new version https://market.ionic.io/starters/whatsapp-viber-video-text-chat-full-app
